name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore TodoApp.sln

    - name: Build
      run: dotnet build TodoApp.sln --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test TodoApp.sln --no-build --verbosity normal --configuration Release

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Build Angular Frontend
      working-directory: ./client
      run: |
        npm install
        npm run build -- --configuration production
